version: '3'

services:
  electrum:
    build:
      context: ./docker/electrum
    environment:
      - ELECTRUM_TESTNET=${ELECTRUM_TESTNET}
      - ELECTRUM_USER=${ELECTRUM_USER}
      - ELECTRUM_PASSWORD=${ELECTRUM_PASSWORD}
    ports:
      - 7000:7000

#  httpie:
#    tty: true
#
#    image: alpine/httpie:latest
#    entrypoint: infinity-run.sh