version: '3'

services:
  electrum:
    build:
      context: ./docker/electrum
    environment:
      - ELECTRUM_DAEMON_ADDRESS=${ELECTRUM_DAEMON_ADDRESS}
      - ELECTRUM_TESTNET=${ELECTRUM_TESTNET}
      - ELECTRUM_USER=${ELECTRUM_USER}
      - ELECTRUM_PASSWORD=${ELECTRUM_PASSWORD}
    volumes:
      - type: bind
        source: ./docker/electrum/data
        target: /home/electrum/.electrum

    ports:
      - 7000:7000